services:
  app:
    container_name: fio-app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      tags:
        - fio-analyzer_app
    ports:
      - "80:80"
    volumes:      
      - ./data/backend/db:/app/db
      - ./data/backend/uploads:/app/uploads
      - ./data/auth/.htpasswd:/app/.htpasswd
      - ./data/auth/.htuploaders:/app/.htuploaders
    #environment:
    #  - VITE_API_URL=${EXTERNAL_URL}/api
    networks:
      - fio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      timeout: 30s
      interval: 30s
      retries: 3

  # SQLite Web-based database administration tool
  #sqlite-web:
  #  container_name: fio-sqlite-web
  #  image: coleifer/sqlite-web:latest
  #  ports:
  #    - "81:8080"
  #  volumes:
  #    - ./data/backend/db:/data
  #  environment:
  #    SQLITE_DATABASE: /data/storage_performance.db
  #  networks:
  #    - fio-network
  #  restart: unless-stopped
  #  healthcheck:
  #    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
  #    timeout: 30s
  #    interval: 30s
  #    retries: 3

networks:
  fio-network:
    driver: bridge 