version: '3.8'

# Production Docker Compose using pre-built images from registry
# Usage: docker compose -f compose.prod.yml up -d

services:
  app:
    container_name: fio-app
    image: docker.io/styliteag/fio-analyzer-app:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    volumes:      
      - ./data/backend/db:/app/db
      - ./data/backend/uploads:/app/uploads
      - ./data/auth/.htpasswd:/app/.htpasswd
      - ./data/auth/.htuploaders:/app/.htuploaders
    networks:
      - fio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/health-check.sh"]
      timeout: 60s
      interval: 30s
      retries: 3

networks:
  fio-network:
    driver: bridge