version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      #- ../backend:/app/backend
      - ./data/sqlite_data:/app/db
    environment:
      - PYTHONPATH=/app
    networks:
      - fio-network

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - fio-network

volumes:
  sqlite_data:

networks:
  fio-network:
    driver: bridge 