services:
  app:
    container_name: fio-app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      args:
        VITE_API_URL: "."
      tags:
        - fio-analyzer_app
    ports:
      - "80:80"
    volumes:      
      - ./data/backend/db:/app/db
      - ./data/backend/uploads:/app/uploads
      - ./data/auth/.htpasswd:/app/.htpasswd
    environment:
      - VITE_API_URL=${EXTERNAL_URL}/api
    networks:
      - fio-network
    restart: unless-stopped
    #healthcheck:
    #  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/test-runs"]
    #  timeout: 30s
    #  interval: 30s
    #  retries: 3

networks:
  fio-network:
    driver: bridge 