version: '3.8'

# Production Docker Compose using pre-built images from registry
# Usage: docker compose -f compose.prod.yml up -d

services:
  nginx:
    container_name: fio-nginx
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_NAMESPACE:-yourusername}/fio-analyzer-nginx:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - fio-network
    restart: unless-stopped

  backend:
    container_name: fio-backend
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_NAMESPACE:-yourusername}/fio-analyzer-backend:${IMAGE_TAG:-latest}
    volumes:      
      - ./data/backend/db:/app/db
      - ./data/backend/uploads:/app/uploads
      - ./data/auth/.htpasswd:/app/.htpasswd
    networks:
      - fio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/test-runs"]
      timeout: 30s
      interval: 30s
      retries: 3

  frontend:
    container_name: fio-frontend
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_NAMESPACE:-yourusername}/fio-analyzer-frontend:${IMAGE_TAG:-latest}
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${EXTERNAL_URL}/api
    networks:
      - fio-network
    restart: unless-stopped

networks:
  fio-network:
    driver: bridge