version: '3.8'

services:
  nginx:
    container_name: fio-nginx
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - fio-network
    restart: unless-stopped

  backend:
    container_name: fio-backend
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    volumes:      
      - ./data/backend/db:/app/db
      - ./data/backend/uploads:/app/uploads
      - ./data/auth/.htpasswd:/app/.htpasswd
    networks:
      - fio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/test-runs"]
      timeout: 30s
      interval: 30s
      retries: 3

  frontend:
    container_name: fio-frontend
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${EXTERNAL_URL}/api
    networks:
      - fio-network
    restart: unless-stopped

networks:
  fio-network:
    driver: bridge 